
# APP CONFIG
spring.application.name=quantitymeasurement
server.port=8080

# MYSQL DATABASE CONFIG

spring.datasource.url=jdbc:mysql://localhost:3306/QuantityUser
spring.datasource.username=root
spring.datasource.password=Muskan@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT CONFIG
jwt.secret=mysupersecretkey123456
jwt.expiration=86400000


# GOOGLE OAUTH2 CONFIG

spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET

spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub